---
# tasks file for common
- name: Wait for instances to become reachable over SSH
  wait_for_connection:
    timeout: 600

- name: Update System
  apt:
    upgrade: yes
    update_cache: true
- name: Ensure packages needed to use the Kubernetes apt repository are installed
  apt:
    state: present
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    update_cache: true
# Docker
- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt and install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: true
# K8s
- name: Ensure Google Cloud public signing key is in keyring
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
    keyring: /usr/share/keyrings/kubernetes-archive-keyring.gpg

- name: Ensure Kubernetes Repo is available
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
- name: Ensure Kubernetes tools are installed
  apt:
    state: present
    pkg:
    - "kubelet={{ KUBERNETES_VERSION }}"
    - "kubeadm={{ KUBERNETES_VERSION }}"
    - "kubectl={{ KUBERNETES_VERSION }}"
    update_cache: true

- name: Ensure newer kubelet version is  not installed on updating
  dpkg_selections:
    name: kubelet
    selection: hold

- name: Ensure newer kubadm version is  not installed on updating
  dpkg_selections:
    name: kubeadm
    selection: hold

- name: Ensure newer kubectl version is  not installed on updating
  dpkg_selections:
    name: kubectl
    selection: hold

- name: Ensure cri-dockerd is installed
  apt:
    deb: https://github.com/Mirantis/cri-dockerd/releases/download/v0.2.2/cri-dockerd_0.2.2.3-0.ubuntu-jammy_amd64.deb
- name: net.ipv4.ip_forward = 1
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
  
    
# Falco

- name: Ensure Falco public signing key is in keyring
  ansible.builtin.apt_key:
    url: https://falco.org/repo/falcosecurity-3672BA8F.asc
    state: present
- name: Ensure Falco Repo is available
  apt_repository:
    repo: "deb https://download.falco.org/packages/deb stable main"
    state: present
    
- name: install headers matching kernel
  apt:
    pkg:
    - "linux-headers-{{ansible_kernel}}"

- name: install falco
  apt:
    pkg:
    - falco
- name: remove swap
  shell: "swapoff -a"